### ISSUE TITLE
Removing indicator from the carousel view

### ISSUE THREAD

**Issue by Khizrum** [sung2063/AndroidSliderViewSample#2]
Dear Sung, Im using your library, and im extremely grateful for the effort you have put in. I wanted to remove the indicator at the bottom, in case there is a single image, so could you please provide that functionality. Ill be grateful if you do this.

**Comment by sung2063** [comment]
Hi Khizrum,

Thank you for your interest on Carousel View library.
Definitely! I will update the features and let you know as soon as possible. :)

Best,
Sung Hyun

**Comment by sung2063** [comment]
Hi Khizrum,

I published AndroidSlideViewLibrary v1.3 which includes the feature of controlling visibility of the tab indicator in Carousel View.

Make sure you update the library to 1.3 and refresh the dependency before use it.
For more information how to visible/ invisible the tab indicator, please check out the latest library release link: https://github.com/sung2063/AndroidSliderViewsLibrary/releases

Best,
Sung Hyun
